name: Interactions
version: '${project.version}'
main: net.quepierts.interactions.Interactions
api-version: 1.13
softdepend: [ ItemAdders ]
authors: [ Louis_Quepierts ]
description: You can add the actions with conditions
commands:
  interactions:
    aliases:
      - 'its'
    permission: "interactions.command"
    permission-message: "You don't have permission to execute this command."